name: 'Go package'
on: [ push ]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        run: |
          go test -race -coverprofile=./coverage.out
          go test -race -cover -coverprofile=./coverage.txt -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CC_TEST_REPORTER_ID }}
