name: 'Go package'
on: [ push ]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        run: |
          go test -race -coverprofile=./c.out
          go test -race -cover -coverprofile=./coverage.txt -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

#      - name: Install Code Climate reporter
#        run: |
#          sudo curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#          sudo chmod +x ./cc-test-reporter
#          sudo ./cc-test-reporter format-coverage -t gocov
#
#      - name: Upload coverage information
#        env:
#          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
#        run: |
#          sudo ./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER_ID
#          sudo ./cc-test-reporter after-build --exit-code 0
